package project.model;
// Generated 16-ene-2021 14:58:06 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Basicdata generated by hbm2java
 */


public class Basicdata implements java.io.Serializable {


    private int idBasicData;
    private String language;
    private String phone;
    private String web;
    
    private Set<Media> medias;

    public Basicdata() {
    }

    public Basicdata(String language, String phone, String web) {
        this.language = language;
        this.phone = phone;
        this.web = web;
    }

    public Basicdata(int idBasicData, String language, String phone, String web) {
        this.idBasicData = idBasicData;
        this.language = language;
        this.phone = phone;
        this.web = web;
    }

    public Basicdata(int idBasicData, String language, String phone, String web, Set<Media> medias) {
        this.idBasicData = idBasicData;
        this.language = language;
        this.phone = phone;
        this.web = web;
        this.medias = medias;
    }

    public int getIdBasicData() {
        return this.idBasicData;
    }

    public void setIdBasicData(int idBasicData) {
        this.idBasicData = idBasicData;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWeb() {
        return this.web;
    }

    public void setWeb(String web) {
        this.web = web;
    }

    public Set<Media> getMedias() {
        return this.medias;
    }

    public void setMedias(Set<Media> medias) {
        this.medias = medias;
    }

}
