package project.model;
// Generated 16-ene-2021 14:58:06 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Media generated by hbm2java
 */

public class Media implements java.io.Serializable {


    private int idMedia;
    private String url;
    

    private Basicdata basicdata;

    public Media() {
    }

    public Media(String url) {
        this.url = url;
    }

    public Media(Basicdata basicdata, String url) {
        this.basicdata = basicdata;
        this.url = url;
    }

    public Media(int idMedia, Basicdata basicdata, String url) {
        this.idMedia = idMedia;
        this.basicdata = basicdata;
        this.url = url;
    }

    public int getIdMedia() {
        return this.idMedia;
    }

    public void setIdMedia(int idMedia) {
        this.idMedia = idMedia;
    }

    public Basicdata getBasicdata() {
        return this.basicdata;
    }

    public void setBasicdata(Basicdata basicdata) {
        this.basicdata = basicdata;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
